seattle_stage/seattle_stage/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve as dj_static_serve

import theater.views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', theater.views.index, name="root_index"),
    #url(r'^admin/', include('registration.urls')),
    url(r'^stage/', include('theater.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^accounts/', include('registration.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
  static_url = '/'.join([p for p in settings.STATIC_URL.split('/') if not p == ''])
  static_url = ''.join([r'^', static_url, r'/(?P<path>.*)$'])
  urlpatterns += [
      url(static_url,
        dj_static_serve,
        {'document_root': settings.STATIC_ROOT})
      ]

seattle_stage/theater/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'theater'
urlpatterns = [
    url(r'^$', views.event_index, name='index'),

    # admin dashboard
    url(r'^admin/$', views.admin_dashboard, name='admin_dashboard'),

    # index pages
    url(r'^suggestions/$', views.suggestions, name='suggestions'),
    url(r'^scene/$', views.scene, name='scene'),

    # calender/day views
    url(r'^events/$',
      views.event_month, name='events_month'),
    url(r'^ajax/events/$',
      views.ajax_update_event_month, name='ajax_events_month'),
    url(r'^events/week/$',
      views.event_week, name='events_week'),
    url(r'^events/day/$',
      views.event_day, name='events_day'),
    url(r'^events/(?P<event_pk>[0-9]+)/$',
      views.event_detail, name='event_detail'),
    url(r'^events/new/$',
      views.event_new, name='event_new'),
    url(r'^events/(?P<event_pk>[0-9]+)/edit/$',
      views.event_edit, name='event_edit'),
    url(r'^events/(?P<event_pk>[0-9]+)/delete/$',
      views.event_delete, name='event_delete'),

    # venues
    url(r'^venues/$',
      views.venue_index, name='venue_index'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/$',
      views.venue_detail, name='venue_detail'),
    url(r'^venues/new/$',
      views.venue_new, name='venue_new'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/edit/$',
      views.venue_edit, name='venue_edit'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/delete/$',
      views.venue_delete, name='venue_delete'),

    # companies
    url(r'^companies/$',
      views.company_index, name='company_index'),
    url(r'^companies/(?P<company_pk>[0-9]+)/$',
      views.company_detail, name='company_detail'),
    url(r'^companies/new/$',
      views.company_new, name='company_new'),
    url(r'^companies/(?P<company_pk>[0-9]+)/edit/$',
      views.company_edit, name='company_edit'),
    url(r'^companies/(?P<company_pk>[0-9]+)/delete/$',
      views.company_delete, name='company_delete'),

    # admin stuff
    url(r'^admin/login/$', auth_views.login, name='admin_login'),
    ]

seattle_stage/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Seattle Stage{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet"
    href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    {% load static %}
    <link rel="stylesheet" href="{% static 'base/style.css' %}">
    <link rel="stylesheet" href="{% static 'base/footer.css' %}">

    {% block stylesheets %}
    {% endblock %}

    {% block leaf_stylesheets %}
      {# This should only be overwritten by leaves -- not templates that  #}
      {# will be further inherited. That way, end pages always have a     #}
      {# handle for their own stylesheets.                                #}
    {% endblock %}

    <link rel="icon" href="{% block favicon %}{% static 'base/axe-icon.png' %}{% endblock %}">

  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top" id="main-nav">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Seattle Stage</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'theater:events_month' %}">Shows</a></li>
            <li><a href="{% url 'theater:scene' %}">Scene</a></li>
            <li><a href="{% url 'theater:suggestions' %}">Featured</a></li>
            {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                role="button" aria-haspopup="true"
                aria-expanded="false"><span class="glyphicon glyphicon-cog"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'theater:admin_dashboard' %}">
                  Admin Dashboard</a></li>
                <li><a href="{% url 'password_change' %}">
                  Change Password</a></li>
                <li><a href="{% url 'logout' %}">
                  Logout</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Create New</li>
                <li><a href="{% url 'theater:venue_new' %}">New
                    Venue</a></li>
                <li><a href="{% url 'theater:company_new' %}">New
                    Company</a></li>
                <li><a href="{% url 'theater:event_new' %}">New
                    Event</a></li>
              </ul>
            </li>
            {% else %}
            <li>
              <a href="{% url 'login' %}">
                <span class="glyphicon glyphicon-log-in"></span>
              </a>
            </li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    {% block jumbotron %}
      <div class="jumbotron fs-jumbotron" id="main-jumbotron">
        <div class="container">
          {% block jumbotron_content %}
          {% endblock %}
        </div>
      </div>
    {% endblock %}

    {% block raw_content %}
      <div class="container" id="contentblock-container">
        {% block content %}{% endblock %}
      </div>
    {% endblock %}

    <footer class="footer">
      <div class="container">
        <p class="text-muted">
        Created by the 
        <a href="//www.frozen-sea-theatre-collective.org/">
          Frozen Sea Theatre Collective</a>. </p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    {% block scripts %}
    {% endblock %}

  </body>

</html>