seattle_stage/seattle_stage/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve as dj_static_serve

import theater.views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', theater.views.index, name="root_index"),
    #url(r'^admin/', include('registration.urls')),
    url(r'^stage/', include('theater.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^accounts/', include('registration.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
  static_url = '/'.join([p for p in settings.STATIC_URL.split('/') if not p == ''])
  static_url = ''.join([r'^', static_url, r'/(?P<path>.*)$'])
  urlpatterns += [
      url(static_url,
        dj_static_serve,
        {'document_root': settings.STATIC_ROOT})
      ]

seattle_stage/theater/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'theater'
urlpatterns = [
    url(r'^$', views.event_index, name='index'),

    # admin dashboard
    url(r'^admin/$', views.admin_dashboard, name='admin_dashboard'),

    # index pages
    url(r'^suggestions/$', views.suggestions, name='suggestions'),
    url(r'^scene/$', views.scene, name='scene'),

    # calender/day views
    url(r'^events/$',
      views.event_month, name='events_month'),
    url(r'^ajax/events/$',
      views.ajax_update_event_month, name='ajax_events_month'),
    url(r'^events/week/$',
      views.event_week, name='events_week'),
    url(r'^events/day/$',
      views.event_day, name='events_day'),
    url(r'^events/(?P<event_pk>[0-9]+)/$',
      views.event_detail, name='event_detail'),
    url(r'^events/new/$',
      views.event_new, name='event_new'),
    url(r'^events/(?P<event_pk>[0-9]+)/edit/$',
      views.event_edit, name='event_edit'),
    url(r'^events/(?P<event_pk>[0-9]+)/delete/$',
      views.event_delete, name='event_delete'),

    # venues
    url(r'^venues/$',
      views.venue_index, name='venue_index'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/$',
      views.venue_detail, name='venue_detail'),
    url(r'^venues/new/$',
      views.venue_new, name='venue_new'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/edit/$',
      views.venue_edit, name='venue_edit'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/delete/$',
      views.venue_delete, name='venue_delete'),

    # companies
    url(r'^companies/$',
      views.company_index, name='company_index'),
    url(r'^companies/(?P<company_pk>[0-9]+)/$',
      views.company_detail, name='company_detail'),
    url(r'^companies/new/$',
      views.company_new, name='company_new'),
    url(r'^companies/(?P<company_pk>[0-9]+)/edit/$',
      views.company_edit, name='company_edit'),
    url(r'^companies/(?P<company_pk>[0-9]+)/delete/$',
      views.company_delete, name='company_delete'),

    # admin stuff
    url(r'^admin/login/$', auth_views.login, name='admin_login'),
    ]

seattle_stage/theater/views/company_views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from theater.models import Event, Venue, Company
from theater.forms import CompanyForm, VenueForm
from theater.filters import CompanyFilter
import theater.form_helpers as form_helpers
import view_helpers

## TODO:
#
#  Date/Times
#    * filtering dashboard (on venue, company, time window, price?,
#      neighborhood, classification, etc.)
#    * month view, week view, day view
#
#  Company view
#    * people, description
#    * recent/upcoming shows they've done
#
#  Venue view
#    * Google maps, info, link to venue website
#    * recent/upcoming shows there



## Company Index ##############################################################
#
#@login_required
def company_index(request):
  companies = Company.objects.all()
  companies_filtered = CompanyFilter(request.GET, queryset=companies)
  context = {
      'companies': companies_filtered,
      }
  return render(request, 'theater/company_index.html', context)
#
#
###############################################################################



## Company Detail #############################################################
#
#@login_required
def company_detail(request, company_pk):
  company = Company.objects.get(pk=company_pk)
  context = {
      'company': company,
      }
  return render(request, 'theater/company_detail.html', context)
#
#
###############################################################################



## New Company ##################################################################
#
@login_required
def company_new(request):
  if request.method == 'POST':
    new_company, form_is_complete, company_form = form_helpers.modelFromFormPost(
        Company, CompanyForm, request)
    if form_is_complete:
      return redirect('theater:admin_dashboard')
  else:
    company_form = CompanyForm()
  context = {
      'form': company_form,
      }
  return render(request, 'theater/company_new.html', context)
#
#
###############################################################################



## Edit Company #################################################################
#
@login_required
def company_edit(request, company_pk):
  company = Company.objects.get(pk=company_pk)
  if request.method == 'POST':
    form_is_complete, company_form = form_helpers.updateModelFromFormPost(
        company, CompanyForm, request)
    if form_is_complete:
      return redirect('theater:admin_dashboard')
  else:
    company_form = CompanyForm(initial=company.formInitialData())

  context = {
      'company_pk': company_pk,
      'form': company_form,
      }

  return render(request, 'theater/company_edit.html', context)
#
#
###############################################################################



## Delete Company ###############################################################
#
@login_required
def company_delete(request, company_pk):
  if request.method == 'POST':
    company = Company.objects.get(pk=company_pk)
    company.delete()
    return redirect('theater:admin_dashboard')
  return redirect('theater:company_detail', company_pk=company_pk)
#
#
###############################################################################

seattle_stage/theater/views/event_views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import Http404
import datetime
from dateutil.relativedelta import relativedelta

from theater.models import Event, Venue, Company
from theater.forms import EventForm
from theater.filters import EventFilter
import view_helpers
import theater.form_helpers as form_helpers


## TODO:
#
#  Date/Times
#    * filtering dashboard (on venue, company, time window, price?,
#      neighborhood, classification, etc.)
#    * month view, week view, day view
#
#  Company view
#    * people, description
#    * recent/upcoming shows they've done
#
#  Venue view
#    * Google maps, info, link to venue website
#    * recent/upcoming shows there



## Events Index View ##########################################################
#
#@login_required
def event_index(request):
  events = Event.objects.all()
  context = {
      'events': events,
      }
  return render(request, 'theater/event_index.html', context)
#
#
###############################################################################



## Events Detail View #########################################################
#
#@login_required
def event_detail(request, event_pk):
  event = Event.objects.get(pk=event_pk)
  context = {
      'event': event,
      }
  return render(request, 'theater/event_detail.html', context)
#
#
###############################################################################



## Month Calendar View ########################################################
#
#@login_required
def event_month(request):
  today = timezone.now()

  mutable_GET = request.GET.copy()

  view_date = datetime.datetime.strptime(mutable_GET.get('date',
    today.strftime('%m/%Y')), '%m/%Y')
  print(view_date)

  if mutable_GET.get('date', None) is None:
    mutable_GET.update({'date': today.strftime('%m/%Y')})
  
  next_month = view_date + relativedelta(months=+1)
  last_month = view_date + relativedelta(months=-1)

  events = Event.objects.all()
  events_filtered = EventFilter(mutable_GET, queryset=events)

  context = {
      'events': events_filtered,
      'year': view_date.year,
      'month': view_date.month,
      'next_month': next_month.strftime('%m/%Y'),
      'last_month': last_month.strftime('%m/%Y'),
      'this_month': today.strftime('%m/%Y'),
      'get_params': mutable_GET,
      }

  return render(request, 'theater/month.html', context)
#
#
###############################################################################



## AJAX Update Month Calendar View ############################################
#
#@login_required
def ajax_update_event_month(request):
  try:
    view_date = datetime.datetime.strptime(request.GET.get('date', ''),
        '%m/%Y')
  except ValueError as e:
    print(e)
    raise Http404
  else:
    print(view_date)

  today = timezone.now()
  next_month = view_date + relativedelta(months=+1)
  last_month = view_date + relativedelta(months=-1)

  events = Event.objects.all()
  events_filtered = EventFilter(request.GET, queryset=events)

  context = {
      'events': events_filtered.qs,
      'year': view_date.year,
      'month': view_date.month,
      'next_month': next_month.strftime('%m/%Y'),
      'last_month': last_month.strftime('%m/%Y'),
      'this_month': today.strftime('%m/%Y'),
      }

  return render(request, 'theater/frags/month_calendar.html', context)
#
#
###############################################################################



## Week Calendar View #########################################################
#
#@login_required
def event_week(request):
  today = timezone.now()

  mutable_GET = request.GET.copy()

  view_date = datetime.datetime.strptime(mutable_GET.get('date',
    today.strftime('%m/%d/%Y')), '%m/%d/%Y')

  view_week = view_helpers.weekNum(view_date)

  if mutable_GET.get('date', None) is None:
    mutable_GET.update({'date': today.strftime('%m/%d/%Y')})
  
  if view_date.day < (view_helpers.weekdaySundayZero(view_date) + 1):
    last_week_adj = view_date.day
  else:
    last_week_adj = view_helpers.weekdaySundayZero(view_date) + 1

  daysleft_month = view_helpers.daysInMonth(view_date) - view_date.day
  daysleft_week = 6 - view_helpers.weekdaySundayZero(view_date)
  if daysleft_month < daysleft_week:
    next_week_adj = daysleft_month + 1
  else:
    next_week_adj = 7 - view_helpers.weekdaySundayZero(view_date)

  next_week = view_date + relativedelta(days=+next_week_adj)
  last_week = view_date + relativedelta(days=-last_week_adj)

  events = Event.objects.all()
  events_filtered = EventFilter(mutable_GET, queryset=events)

  context = {
      'events': events_filtered,
      'year': view_date.year,
      'month': view_date.month,
      'week': view_week,
      'next_week': next_week.strftime('%m/%d/%Y'),
      'last_week': last_week.strftime('%m/%d/%Y'),
      'get_params': mutable_GET,
      }

  return render(request, 'theater/week.html', context)
#
#
###############################################################################



## Day List View ##############################################################
#
#  This provides a list of all the Event objects that are happening on the
#  given date (year, month, day).
#
#@login_required
def event_day(request):
  today = timezone.now()

  mutable_GET = request.GET.copy()
  if mutable_GET.get('year', None) is None:
    mutable_GET.update({'year': today.year})
  if mutable_GET.get('month', None) is None:
    mutable_GET.update({'month': today.month})
  if mutable_GET.get('day', None) is None:
    mutable_GET.update({'day': today.day})
  
  year = mutable_GET.get('year', today.year)
  month = mutable_GET.get('month', today.month)
  day = mutable_GET.get('day', today.day)

  view_date = datetime.date(int(year), int(month), int(day))

  yesterday = view_date + relativedelta(days=-1)
  tomorrow = view_date + relativedelta(days=+1)

  events = Event.objects.all()
  events_filtered = EventFilter(mutable_GET, queryset=events)

  context = {
      'events': events_filtered,
      'year': year,
      'month': month,
      'day': day,
      'tomorrow': tomorrow,
      'yesterday': yesterday,
      'get_params': mutable_GET,
      }

  return render(request, 'theater/day.html', context)
#
#
###############################################################################



## Event New ##################################################################
#
@login_required
def event_new(request):
  if request.method == 'POST':
    new_event, form_is_complete, event_form = form_helpers.modelFromFormPost(
        Event, EventForm, request)
    if form_is_complete:
      return redirect('theater:admin_dashboard')
  else:
    event_form = EventForm()
  context = {
      'form': event_form,
      }
  return render(request, 'theater/event_new.html', context)
#
#
###############################################################################



## Event Edit #################################################################
#
@login_required
def event_edit(request, event_pk):
  event = Event.objects.get(pk=event_pk)
  if request.method == 'POST':
    form_is_complete, event_form = form_helpers.updateModelFromFormPost(
        event, EventForm, request)
    if form_is_complete:
      return redirect('theater:admin_dashboard')
  else:
    event_form = EventForm(initial=event.formInitialData())

  context = {
      'event_pk': event_pk,
      'form': event_form,
      }

  return render(request, 'theater/event_edit.html', context)
#
#
###############################################################################



## Event Delete ###############################################################
#
@login_required
def event_delete(request, event_pk):
  if request.method == 'POST':
    event = Event.objects.get(pk=event_pk)
    event.delete()
    return redirect('theater:admin_dashboard')
  return redirect('theater:event_detail', event_pk=event_pk)
#
#
###############################################################################

seattle_stage/theater/views/general_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import datetime

import view_helpers
from theater.models import Venue, Company, Event
from theater.forms import VenueForm, CompanyForm, EventForm
from theater.filters import EventFilter

#@login_required
def index(request):
  today = timezone.now()
  week = view_helpers.weekNum(today)
  events = Event.objects.all()
  filtration = {
          'date': today.strftime('%m/%Y'),
          'featured': True,
          }
  events_filtered = EventFilter(filtration, queryset=events)
  context = {
      'today': today,
      'week': week,
      'events': events_filtered.qs,
      }
  return render(request, 'theater/index.html', context)

#@login_required
def suggestions(request):
  events = Event.objects.filter(featured=True)
  context = {
      'features': events,
      }
  return render(request, 'theater/suggestions.html', context)

#@login_required
def scene(request):
  return render(request, 'theater/scene.html')

@login_required
def admin_dashboard(request):
  venues = Venue.objects.all()
  companies = Company.objects.all()
  events = Event.objects.all()

  venue_form_pairs = [
      view_helpers.objectFormPair(v, VenueForm) for v in venues ]
  company_form_pairs = [
      view_helpers.objectFormPair(c, CompanyForm) for c in companies ]
  event_form_pairs = [
      view_helpers.objectFormPair(e, EventForm) for e in events ]

  context = {
      'venue_form_pairs': venue_form_pairs,
      'company_form_pairs': company_form_pairs,
      'event_form_pairs': event_form_pairs,
      }

  return render(request, 'theater/admin_dashboard.html', context)

seattle_stage/theater/templates/theater/frags/admin_company_detail.html
<div class="container admin-detail-container">
  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Name:</span>
    </div>
    <div class="col-md-9">
      {{ company.name }}
      {% if company.brief_name %} ({{ company.brief_name }}) {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Website:</span>
    </div>
    <div class="col-md-9">
      <a href="{{ company.website_url }}">{{ company.website_url }}</a>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Classification:</span>
    </div>
    <div class="col-md-9">
      {{ company.classification }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Picture:</span>
    </div>
    <div class="col-md-9">
      {{ company.image }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Description:</span>
    </div>
    <div class="col-md-9">
      {{ company.description }}
    </div>
  </div>

  <div class="admin-detail-dash">
    <div class="admin-detail-dash-button admin-detail-dash-button-delete">
      <form method="post"
        action="{% url 'theater:company_delete' company_pk=company.pk %}">
        {% csrf_token %}
        <span class="admin-detail-dash-button-delete-pop">
          <a class="popover-link">
            <span id="delete-trash" class="glyphicon glyphicon-trash"></span>
          </a>
        </span>
      </form>
    </div>
    <div class="admin-detail-dash-button">
      <a href="{% url 'theater:company_edit' company_pk=company.pk %}">
        <span class="glyphicon glyphicon-edit"></span>
      </a>
    </div>
    <div class="admin-detail-dash-button">
      <a href="{% url 'theater:company_detail' company_pk=company.pk %}">
        <span class="glyphicon glyphicon-eye-open"></span>
      </a>
    </div>
  </div>

</div>

seattle_stage/theater/templates/theater/frags/admin_event_detail.html
<div class="container admin-detail-container">
  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Name:</span>
    </div>
    <div class="col-md-9">
      {{ event.name }}
      {% if event.brief_name %} ({{ event.brief_name }}) {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Featured:</span>
    </div>
    <div class="col-md-9">
      {% if event.featured %}
      <span class="glyphicon glyphicon-ok"></span>
      {% else %}
      <span class="glyphicon glyphicon-remove"></span>
      {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Website:</span>
    </div>
    <div class="col-md-9">
      <a href="{{ event.website_url }}">{{ event.website_url }}</a>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Company:</span>
    </div>
    <div class="col-md-9">
      {{ event.company }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Venue:</span>
    </div>
    <div class="col-md-9">
      {{ event.venue }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Date:</span>
    </div>
    <div class="col-md-9">
      {{ event.date_and_time|date:"D, M j, Y g:i A" }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Length:</span>
    </div>
    <div class="col-md-9">
      {{ event.show_length }} hours
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Price:</span>
    </div>
    <div class="col-md-9">
      ${{ event.ticket_price }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Tickets:</span>
    </div>
    <div class="col-md-9">
      <a href="{{ event.ticket_url }}">{{ event.ticket_url }}</a>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Picture:</span>
    </div>
    <div class="col-md-9">
      {{ event.image }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Blurb:</span>
    </div>
    <div class="col-md-9">
      {{ event.blurb }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Description:</span>
    </div>
    <div class="col-md-9">
      {{ event.description }}
    </div>
  </div>

  <div class="admin-detail-dash">
    <div class="admin-detail-dash-button admin-detail-dash-button-delete">
      <form method="post"
        action="{% url 'theater:event_delete' event_pk=event.pk %}">
        {% csrf_token %}
        <span class="admin-detail-dash-button-delete-pop">
          <a class="popover-link">
            <span id="delete-trash" class="glyphicon glyphicon-trash"></span>
          </a>
        </span>
      </form>
    </div>
    <div class="admin-detail-dash-button">
      <a href="{% url 'theater:event_edit' event_pk=event.pk %}">
        <span class="glyphicon glyphicon-edit"></span>
      </a>
    </div>
    <div class="admin-detail-dash-button">
      <a href="{% url 'theater:event_detail' event_pk=event.pk %}">
        <span class="glyphicon glyphicon-eye-open"></span>
      </a>
    </div>
  </div>

</div>

seattle_stage/theater/templates/theater/frags/admin_venue_detail.html
<div class="container admin-detail-container">
  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Name:</span>
    </div>
    <div class="col-md-9">
      {{ venue.name }}
      {% if venue.brief_name %} ({{ venue.brief_name }}) {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Website:</span>
    </div>
    <div class="col-md-9">
      <a href="{{ venue.website_url }}">{{ venue.website_url }}</a>
    </div>
  </div>

  <div class="row">
    <div class="admin-detail-address">
      <div class="col-md-3">
        <span class="admin-detail-label">Address:</span>
      </div>
      <div class="col-md-9">
        {{ venue.street_address }} <br/>
        {{ venue.city }}, {{ venue.state }} {{ venue.zip_code }}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Picture:</span>
    </div>
    <div class="col-md-9">
      {{ venue.image }}
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <span class="admin-detail-label">Description:</span>
    </div>
    <div class="col-md-9">
      {{ venue.description }}
    </div>
  </div>

  <div class="admin-detail-dash">
    <div class="admin-detail-dash-button admin-detail-dash-button-delete">
      <form method="post"
        action="{% url 'theater:venue_delete' venue_pk=venue.pk %}">
        {% csrf_token %}
        <span class="admin-detail-dash-button-delete-pop">
          <a class="popover-link">
            <span id="delete-trash" class="glyphicon glyphicon-trash"></span>
          </a>
        </span>
      </form>
    </div>
    <div class="admin-detail-dash-button">
      <a href="{% url 'theater:venue_edit' venue_pk=venue.pk %}">
        <span class="glyphicon glyphicon-edit"></span>
      </a>
    </div>
    <div class="admin-detail-dash-button">
      <a href="{% url 'theater:venue_detail' venue_pk=venue.pk %}">
        <span class="glyphicon glyphicon-eye-open"></span>
      </a>
    </div>
  </div>

</div>

seattle_stage/theater/templates/theater/frags/month_calendar.html
{% load events_calendar_tags %}

<div class="month-calendar-wrapper" id="month-calendar">
  {% events_month_calendar year month events %}
</div>

<div class="month-buttons">
  <div class="col-sm-4 last-month-button">
    <a class="fs-btn fs-btn-trans btn" onclick="ajaxUpdateCalendar('{{ last_month }}')">Previous</a>
  </div>
  <div class="col-sm-4 this-month-button">
    <a class="fs-btn fs-btn-trans btn" onclick="ajaxUpdateCalendar('{{ this_month }}')">This Month</a>
  </div>
  <div class="col-sm-4 next-month-button">
    <a class="fs-btn fs-btn-trans btn" onclick="ajaxUpdateCalendar('{{ next_month }}')">Next</a>
  </div>
</div>