seattle_stage/seattle_stage/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve as dj_static_serve

import theater.views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', theater.views.index, name="root_index"),
    #url(r'^admin/', include('registration.urls')),
    url(r'^stage/', include('theater.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^accounts/', include('registration.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
  static_url = '/'.join([p for p in settings.STATIC_URL.split('/') if not p == ''])
  static_url = ''.join([r'^', static_url, r'/(?P<path>.*)$'])
  urlpatterns += [
      url(static_url,
        dj_static_serve,
        {'document_root': settings.STATIC_ROOT})
      ]

seattle_stage/theater/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'theater'
urlpatterns = [
    url(r'^$', views.event_index, name='index'),

    # admin dashboard
    url(r'^admin/$', views.admin_dashboard, name='admin_dashboard'),

    # index pages
    url(r'^suggestions/$', views.suggestions, name='suggestions'),
    url(r'^scene/$', views.scene, name='scene'),

    # calender/day views
    url(r'^events/$',
      views.event_month, name='events_month'),
    url(r'^ajax/events/$',
      views.ajax_update_event_month, name='ajax_events_month'),
    url(r'^events/week/$',
      views.event_week, name='events_week'),
    url(r'^events/day/$',
      views.event_day, name='events_day'),
    url(r'^events/(?P<event_pk>[0-9]+)/$',
      views.event_detail, name='event_detail'),
    url(r'^events/new/$',
      views.event_new, name='event_new'),
    url(r'^events/(?P<event_pk>[0-9]+)/edit/$',
      views.event_edit, name='event_edit'),
    url(r'^events/(?P<event_pk>[0-9]+)/delete/$',
      views.event_delete, name='event_delete'),

    # venues
    url(r'^venues/$',
      views.venue_index, name='venue_index'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/$',
      views.venue_detail, name='venue_detail'),
    url(r'^venues/new/$',
      views.venue_new, name='venue_new'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/edit/$',
      views.venue_edit, name='venue_edit'),
    url(r'^venues/(?P<venue_pk>[0-9]+)/delete/$',
      views.venue_delete, name='venue_delete'),

    # companies
    url(r'^companies/$',
      views.company_index, name='company_index'),
    url(r'^companies/(?P<company_pk>[0-9]+)/$',
      views.company_detail, name='company_detail'),
    url(r'^companies/new/$',
      views.company_new, name='company_new'),
    url(r'^companies/(?P<company_pk>[0-9]+)/edit/$',
      views.company_edit, name='company_edit'),
    url(r'^companies/(?P<company_pk>[0-9]+)/delete/$',
      views.company_delete, name='company_delete'),

    # admin stuff
    url(r'^admin/login/$', auth_views.login, name='admin_login'),
    ]

seattle_stage/theater/views/company_views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from theater.models import Event, Venue, Company
from theater.forms import CompanyForm, VenueForm
from theater.filters import CompanyFilter
import theater.form_helpers as form_helpers
import view_helpers

## TODO:
#
#  Date/Times
#    * filtering dashboard (on venue, company, time window, price?,
#      neighborhood, classification, etc.)
#    * month view, week view, day view
#
#  Company view
#    * people, description
#    * recent/upcoming shows they've done
#
#  Venue view
#    * Google maps, info, link to venue website
#    * recent/upcoming shows there



## Company Index ##############################################################
#
#@login_required
def company_index(request):
  companies = Company.objects.all()
  companies_filtered = CompanyFilter(request.GET, queryset=companies)
  context = {
      'companies': companies_filtered,
      }
  return render(request, 'theater/company_index.html', context)
#
#
###############################################################################



## Company Detail #############################################################
#
#@login_required
def company_detail(request, company_pk):
  company = Company.objects.get(pk=company_pk)
  context = {
      'company': company,
      }
  return render(request, 'theater/company_detail.html', context)
#
#
###############################################################################



## New Company ##################################################################
#
@login_required
def company_new(request):
  if request.method == 'POST':
    new_company, form_is_complete, company_form = form_helpers.modelFromFormPost(
        Company, CompanyForm, request)
    if form_is_complete:
      return redirect('theater:admin_dashboard')
  else:
    company_form = CompanyForm()
  context = {
      'form': company_form,
      }
  return render(request, 'theater/company_new.html', context)
#
#
###############################################################################



## Edit Company #################################################################
#
@login_required
def company_edit(request, company_pk):
  company = Company.objects.get(pk=company_pk)
  if request.method == 'POST':
    form_is_complete, company_form = form_helpers.updateModelFromFormPost(
        company, CompanyForm, request)
    if form_is_complete:
      return redirect('theater:admin_dashboard')
  else:
    company_form = CompanyForm(initial=company.formInitialData())

  context = {
      'company_pk': company_pk,
      'form': company_form,
      }

  return render(request, 'theater/company_edit.html', context)
#
#
###############################################################################



## Delete Company ###############################################################
#
@login_required
def company_delete(request, company_pk):
  if request.method == 'POST':
    company = Company.objects.get(pk=company_pk)
    company.delete()
    return redirect('theater:admin_dashboard')
  return redirect('theater:company_detail', company_pk=company_pk)
#
#
###############################################################################

seattle_stage/theater/views/event_views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import Http404
import datetime
from dateutil.relativedelta import relativedelta

from theater.models import Event, Venue, Company
from theater.forms import EventForm
from theater.filters import EventFilter
import view_helpers
import theater.form_helpers as form_helpers


## TODO:
#
#  Date/Times
#    * filtering dashboard (on venue, company, time window, price?,
#      neighborhood, classification, etc.)
#    * month view, week view, day view
#
#  Company view
#    * people, description
#    * recent/upcoming shows they've done
#
#  Venue view
#    * Google maps, info, link to venue website
#    * recent/upcoming shows there



## Events Index View ##########################################################
#
#@login_required
def event_index(request):
  events = Event.objects.all()
  context = {
      'events': events,
      }
  return render(request, 'theater/event_index.html', context)
#
#
###############################################################################



## Events Detail View #########################################################
#
#@login_required
def event_detail(request, event_pk):
  event = Event.objects.get(pk=event_pk)
  context = {
      'event': event,
      }
  return render(request, 'theater/event_detail.html', context)
#
#
###############################################################################



## Month Calendar View ########################################################
#
#@login_required
def event_month(request):
  today = timezone.now()

  mutable_GET = request.GET.copy()

  view_date = datetime.datetime.strptime(mutable_GET.get('date',
    today.strftime('%m/%Y')), '%m/%Y')
  print(view_date)

  if mutable_GET.get('date', None) is None:
    mutable_GET.update({'date': today.strftime('%m/%Y')})
  
  next_month = view_date + relativedelta(months=+1)
  last_month = view_date + relativedelta(months=-1)

  events = Event.objects.all()
  events_filtered = EventFilter(mutable_GET, queryset=events)

  context = {
      'events': events_filtered,
      'year': view_date.year,
      'month': view_date.month,
      'next_month': next_month.strftime('%m/%Y'),
      'last_month': last_month.strftime('%m/%Y'),
      'this_month': today.strftime('%m/%Y'),
      'get_params': mutable_GET,
      }

  return render(request, 'theater/month.html', context)
#
#
###############################################################################



## AJAX Update Month Calendar View ############################################
#
#@login_required
def ajax_update_event_month(request):
  try:
    view_date = datetime.datetime.strptime(request.GET.get('date', ''),
        '%m/%Y')
  except ValueError as e:
    print(e)
    raise Http404
  else:
    print(view_date)

  today = timezone.now()
  next_month = view_date + relativedelta(months=+1)
  last_month = view_date + relativedelta(months=-1)

  events = Event.objects.all()
  events_filtered = EventFilter(request.GET, queryset=events)

  context = {
      'events': events_filtered.qs,
      'year': view_date.year,
      'month': view_date.month,
      'next_month': next_month.strftime('%m/%Y'),
      'last_month': last_month.strftime('%m/%Y'),
      'this_month': today.strftime('%m/%Y'),
      }

  return render(request, 'theater/frags/month_calendar.html', context)
#
#
###############################################################################



## Week Calendar View #########################################################
#
#@login_required
def event_week(request):
  today = timezone.now()

  mutable_GET = request.GET.copy()

  view_date = datetime.datetime.strptime(mutable_GET.get('date',
    today.strftime('%m/%d/%Y')), '%m/%d/%Y')

  view_week = view_helpers.weekNum(view_date)

  if mutable_GET.get('date', None) is None:
    mutable_GET.update({'date': today.strftime('%m/%d/%Y')})
  
  if view_date.day < (view_helpers.weekdaySundayZero(view_date) + 1):
    last_week_adj = view_date.day
  else:
    last_week_adj = view_helpers.weekdaySundayZero(view_date) + 1

  daysleft_month = view_helpers.daysInMonth(view_date) - view_date.day
  daysleft_week = 6 - view_helpers.weekdaySundayZero(view_date)
  if daysleft_month < daysleft_week:
    next_week_adj = daysleft_month + 1
  else:
    next_week_adj = 7 - view_helpers.weekdaySundayZero(view_date)

  next_week = view_date + relativedelta(days=+next_week_adj)
  last_week = view_date + relativedelta(days=-last_week_adj)

  events = Event.objects.all()
  events_filtered = EventFilter(mutable_GET, queryset=events)

  context = {
      'events': events_filtered,
      'year': view_date.year,
      'month': view_date.month,
      'week': view_week,
      'next_week': next_week.strftime('%m/%d/%Y'),
      'last_week': last_week.strftime('%m/%d/%Y'),
      'get_params': mutable_GET,
      }

  return render(request, 'theater/week.html', context)
#
#
###############################################################################



## Day List View ##############################################################
#
#  This provides a list of all the Event objects that are happening on the
#  given date (year, month, day).
#
#@login_required
def event_day(request):
  today = timezone.now()

  mutable_GET = request.GET.copy()
  if mutable_GET.get('year', None) is None:
    mutable_GET.update({'year': today.year})
  if mutable_GET.get('month', None) is None:
    mutable_GET.update({'month': today.month})
  if mutable_GET.get('day', None) is None:
    mutable_GET.update({'day': today.day})
  
  year = mutable_GET.get('year', today.year)
  month = mutable_GET.get('month', today.month)
  day = mutable_GET.get('day', today.day)

  view_date = datetime.date(int(year), int(month), int(day))

  yesterday = view_date + relativedelta(days=-1)
  tomorrow = view_date + relativedelta(days=+1)

  events = Event.objects.all()
  events_filtered = EventFilter(mutable_GET, queryset=events)

  context = {
      'events': events_filtered,
      'year': year,
      'month': month,
      'day': day,
      'tomorrow': tomorrow,
      'yesterday': yesterday,
      'get_params': mutable_GET,
      }

  return render(request, 'theater/day.html', context)
#
#
###############################################################################



## Event New ##################################################################
#
@login_required
def event_new(request):
  if request.method == 'POST':
    new_event, form_is_complete, event_form = form_helpers.modelFromFormPost(
        Event, EventForm, request)
    if form_is_complete:
      return redirect('theater:admin_dashboard')
  else:
    event_form = EventForm()
  context = {
      'form': event_form,
      }
  return render(request, 'theater/event_new.html', context)
#
#
###############################################################################



## Event Edit #################################################################
#
@login_required
def event_edit(request, event_pk):
  event = Event.objects.get(pk=event_pk)
  if request.method == 'POST':
    form_is_complete, event_form = form_helpers.updateModelFromFormPost(
        event, EventForm, request)
    if form_is_complete:
      return redirect('theater:admin_dashboard')
  else:
    event_form = EventForm(initial=event.formInitialData())

  context = {
      'event_pk': event_pk,
      'form': event_form,
      }

  return render(request, 'theater/event_edit.html', context)
#
#
###############################################################################



## Event Delete ###############################################################
#
@login_required
def event_delete(request, event_pk):
  if request.method == 'POST':
    event = Event.objects.get(pk=event_pk)
    event.delete()
    return redirect('theater:admin_dashboard')
  return redirect('theater:event_detail', event_pk=event_pk)
#
#
###############################################################################

seattle_stage/theater/views/general_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import datetime

import view_helpers
from theater.models import Venue, Company, Event
from theater.forms import VenueForm, CompanyForm, EventForm
from theater.filters import EventFilter

#@login_required
def index(request):
  today = timezone.now()
  week = view_helpers.weekNum(today)
  events = Event.objects.all()
  filtration = {
          'date': today.strftime('%m/%Y'),
          'featured': True,
          }
  events_filtered = EventFilter(filtration, queryset=events)
  context = {
      'today': today,
      'week': week,
      'events': events_filtered.qs,
      }
  return render(request, 'theater/index.html', context)

#@login_required
def suggestions(request):
  events = Event.objects.filter(featured=True)
  context = {
      'features': events,
      }
  return render(request, 'theater/suggestions.html', context)

#@login_required
def scene(request):
  return render(request, 'theater/scene.html')

@login_required
def admin_dashboard(request):
  venues = Venue.objects.all()
  companies = Company.objects.all()
  events = Event.objects.all()

  venue_form_pairs = [
      view_helpers.objectFormPair(v, VenueForm) for v in venues ]
  company_form_pairs = [
      view_helpers.objectFormPair(c, CompanyForm) for c in companies ]
  event_form_pairs = [
      view_helpers.objectFormPair(e, EventForm) for e in events ]

  context = {
      'venue_form_pairs': venue_form_pairs,
      'company_form_pairs': company_form_pairs,
      'event_form_pairs': event_form_pairs,
      }

  return render(request, 'theater/admin_dashboard.html', context)

seattle_stage/theater/templates/theater/admin_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    {% load static %}
    <link rel="stylesheet" href="{% static 'theater/login_style.css' %}">

    <link rel="icon" href="{% static 'base/axe-icon.png' %}">

  </head>

  <body>

    <div class="container">

      <form class="form-signin" method="post" action="{% url 'login' %}">
        {% csrf_token %}

        {% if form.errors %}
          <div class="alert alert-danger">
            <span class="glyphicon glyphicon-warning-sign"></span>
            <strong>Oops.</strong> Your username and password did not match.
            Please try again.
          </div>
        {% endif %}

        {% load widget_tweaks %}
        {% render_field form.username class="form-control" placeholder="Username" %}
        {% render_field form.password class="form-control" placeholder="Password" %}

        {% if next %}
          <input type="hidden" name="next" value="{{ next }}"/>
        {% else %}
          <input type="hidden" name="next" value="{% url 'forum:index' %}"/>
        {% endif %}

        <button class="btn btn-default btn-block" id="login-button" type="submit">
          Sign In
        </button>
      </form>

    </div> <!-- /container -->

  </body>
</html>

seattle_stage/theater/templates/theater/company_edit.html
{% extends 'base/base.html' %}

{% block jumbotron %}
{% endblock %}

{% block content %}

  <div class="company-form">
    <div class="edit-company-form" id="company-form">

      {% url 'theater:company_edit' company_pk=company_pk as post_url %}
      {% url 'theater:admin_dashboard' as cancel_url %}
      {% include 'theater/forms/company_form.html' with post_url=post_url cancel_url=cancel_url %}

    </div>
  </div>

{% endblock %}

seattle_stage/theater/templates/theater/company_new.html
{% extends 'base/base.html' %}

{% block jumbotron %}
{% endblock %}

{% block content %}

  <div class="company-form">
    <div class="new-company-form" id="company-form">

      {% url 'theater:company_new' as post_url %}
      {% url 'theater:admin_dashboard' as cancel_url %}
      {% include 'theater/forms/company_form.html' with post_url=post_url cancel_url=cancel_url %}

    </div>
  </div>

{% endblock %}

seattle_stage/theater/templates/theater/event_detail_frag.html
{% load markup_tags %}

<div class="col-md-8">
  <div class="container-fluid">
    <h2 class="page-header">
      {{ event.name }} <br/>
      <span class="text-muted">by 
        <a href="{% url 'theater:company_detail' company_pk=event.company.pk %}">{{ event.company }}</a></span>
    </h2>

    <div class="row">
      <div class="col-md-12">
        <p class="lead">
          {{ event.date_and_time|date:"D, M j, Y g:i A" }} at
          <a href="{% url 'theater:venue_detail' venue_pk=event.venue.pk %}">
            {{ event.venue }}
          </a>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        {{ event.description|apply_markup:"markdown" }}
      </div>
    </div>

  </div>
</div>

<div class="col-md-4">
  <div class="container-fluid">
    {% if event.image %}
    <div class="row">
      <img src="{{ event.image.url }}" width="100%">
    </div>
    {% endif %}

    <div class="row">
      <div class="col-md-3">
        <span class="admin-detail-label">Name:</span>
      </div>
      <div class="col-md-9">
        {{ event.name }}
        {% if event.brief_name %} ({{ event.brief_name }}) {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <span class="admin-detail-label">Company:</span>
      </div>
      <div class="col-md-9">
        <a href="{% url 'theater:company_detail' company_pk=event.company.pk %}">
          {{ event.company }}
        </a>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <span class="admin-detail-label">Venue:</span>
      </div>
      <div class="col-md-9">
        <a href="{% url 'theater:venue_detail' venue_pk=event.venue.pk %}">
          {{ event.venue }}
        </a>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <span class="admin-detail-label">Date:</span>
      </div>
      <div class="col-md-9">
        {{ event.date_and_time|date:"D, M j, Y g:i A" }}
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <span class="admin-detail-label">Website:</span>
      </div>
      <div class="col-md-9">
        <a href="{{ event.website_url }}">{{ event.website_url }}</a>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <span class="admin-detail-label">Length:</span>
      </div>
      <div class="col-md-9">
        {% if event.show_length %}
        {{ event.show_length }} hours
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <span class="admin-detail-label">Price:</span>
      </div>
      <div class="col-md-9">
        {% if event.ticket_price %}
        ${{ event.ticket_price }}
        {% endif %}
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <span class="admin-detail-label">Tickets:</span>
      </div>
      <div class="col-md-9">
        <a href="{{ event.ticket_url }}">{{ event.ticket_url }}</a>
      </div>
    </div>

  </div>
</div>

seattle_stage/theater/templates/theater/event_new.html
{% extends 'base/base.html' %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.45/css/bootstrap-datetimepicker.min.css">
{% endblock %}

{% block jumbotron %}
{% endblock %}

{% block content %}

  <div class="event-form">
    <div class="new-event-form" id="venue-form">
      {% url 'theater:event_new' as post_url %}
      {% url 'theater:admin_dashboard' as cancel_url %}
      {% include 'theater/forms/event_form.html' with post_url=post_url cancel_url=cancel_url %}
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script
    src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
  <script
    src="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
  <script>
    $(function () {
      $('.datetimepicker').datetimepicker();
    });
  </script>
{% endblock %}

seattle_stage/theater/templates/theater/index.html
{% extends 'theater/splash_base.html' %}
{% load static %}
{% load events_calendar_tags %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'theater/index.css' %}">
  <link rel="stylesheet" href="{% static 'theater/style.css' %}">
{% endblock %}


{% block jumbotron_content %}

  <div class="welcome">
    <div class="welcome-title">
      Seattle Stage
    </div>
    <div class="welcome-blurb">
      Connecting Seattle's vibrant theatre scene.
    </div>
  </div>

{% endblock %}


{% block raw_content %}


<div class="index-row-container index-row-container-odd">
  <div class="container">
    <div class="row index-row">
      <div class="col-md-4 index-banner-item">
        <a href="{% url 'theater:events_month' %}">
          <span class="glyphicon glyphicon-calendar index-banner-icon"></span>
          <h2>Find a Show</h2>
          <p class="lead">There's always a lot going on in the Seattle theater
          scene. Find the show that's right for you!</p>
        </a>
      </div>
      <div class="col-md-4 index-banner-item">
        <a href="{% url 'theater:suggestions' %}">
          <span class="glyphicon glyphicon-thumbs-up index-banner-icon"></span>
          <h2>Our Suggestions</h2>
          <p class="lead">Looking for some recommendations? Find out what we
          liked or are looking forward to.</p>
        </a>
      </div>
      <div class="col-md-4 index-banner-item">
        <a href="{% url 'theater:scene' %}">
          <!--<span class="glyphicon glyphicon-user index-banner-icon"></span>-->
          <span class="index-banner-icon"><i class="fa fa-users" aria-hidden="true"></i></span>
          <h2>Local Scene</h2>
          <p class="lead">Find out more about the theater companies and venues
          that make Seattle one of the best theater cities in the country.</p>
        </a>
      </div>
    </div>
    {% if events %}
    <div class="row index-row">
      <div class="index-calendar-wrapper">
        <div class="index-calendar">
          <div class="month-calendar-wrapper">
            {% events_week_calendar today.year today.month week events %}
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>

<div class="index-row-container index-row-container-even">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="index-row-title">Meet Our Team</div>
      </div>
    </div>
    <div class="row index-row">
      <div class="col-md-3 index-banner-item team-member">
        <img src="{% static 'base/claire-square.png' %}" alt="Claire Koleske">
        <div class="team-member-name">Claire Koleske</div>
        <div class="team-member-tag">Artistic Director <br> 
          <a class="no-color"
             href="http://www.frozen-sea-theatre-collective.org/">Frozen Sea
             Theatre Collective</a></div>
      </div>
      <div class="col-md-3 index-banner-item team-member">
        <img src="{% static 'base/billy-square.png' %}" alt="William Zimmerman">
        <div class="team-member-name">William Zimmerman</div>
        <div class="team-member-tag">Artistic Director <br>
          <a class="no-color"
             href="http://www.frozen-sea-theatre-collective.org/">Frozen Sea
             Theatre Collective</a></div>
      </div>
      <div class="col-md-3 index-banner-item team-member">
        <img src="{% static 'base/tasha-edgy-square.png' %}" alt="Tasha Newell">
        <div class="team-member-name">Tasha Newell</div>
        <div class="team-member-tag">Muse / Production Manager <br>
          <a class="no-color"
             href="http://www.frozen-sea-theatre-collective.org/">Frozen Sea
             Theatre Collective</a></div>
      </div>
      <div class="col-md-3 index-banner-item team-member">
        <img src="{% static 'base/andrew-square.png' %}" alt="Andrew Milligan">
        <div class="team-member-name">Andrew Milligan</div>
        <div class="team-member-tag">Software Engineer <br>
          <a class="no-color"
             href="http://www.frozen-sea-theatre-collective.org/">Frozen Sea
             Theatre Collective</a></div>
      </div>
    </div>
  </div>
</div>


{% if events %}
<div class="container marketing index-row-container-odd">
  <div class="row">
    <div class="col-md-12">
      <div class="index-row-title index-row-title-even">Featured Productions</div>
    </div>
  </div>

  {% for feature in events %}
  <a class="no-color" href="{% url 'theater:event_detail' event_pk=feature.pk %}">
    <div class="row featurette index-row">
      <div class="col-md-7">
        <h2 class="featurette-heading">
          {{ feature.name }} </br>
          <span class="text-muted">by {{ feature.company }}</span>
        </h2>
        <p class="lead">{{ feature.blurb }}</p>
      </div>
      <div class="col-md-5">
        <img class="featurette-image img-responsive center-block"
             src="{{ feature.image.url }}" alt="featurette poster">
      </div>
    </div>
  </a>
  <hr class="featurette-divider">
  {% endfor %}

</div>
{% endif %}


{% endblock %}

{% block scripts %}

  <script>
    function enter() {
      document.getElementById('tasha-hello').style.display = 'none';
    }
      
    $(document).ready(function (){
      $('.tasha-img-wrapper').css({'height': $(window).height()});
      $('.enter-text').css({'margin-top': $(window).height() / 3});
    });
  </script>

{% endblock %}

seattle_stage/theater/templates/theater/venue_index.html
{% extends 'theater/splash_base.html' %}

{% block jumbotron_content %}

  <div class="jumbo-plain-title">
    <h1>Venues</h1>
    <p class="lead">Explore the spaces that bring art to life onstage.</p>
  </div>

{% endblock %}

{% block content %}

  <div class="filter-dash">
    {% include 'theater/forms/venue_filter_form.html' with form=venues.form %}
  </div>

  <div class="container-fluid">
    {% for venue in venues.qs %}
    <div class="row">
      <div class="col-md-12">
        <h2><a href="{% url 'theater:venue_detail' venue_pk=venue.pk %}">{{ venue.name }}</a></h2>
        <p>{{ venue.description }}</p>
      </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

seattle_stage/theater/templates/theater/venue_new.html
{% extends 'base/base.html' %}

{% block jumbotron %}
{% endblock %}

{% block content %}

  <div class="venue-form">
    <div class="new-venue-form" id="venue-form">
      {% url 'theater:venue_new' as post_url %}
      {% url 'theater:admin_dashboard' as cancel_url %}
      {% include 'theater/forms/venue_form.html' with post_url=post_url cancel_url=cancel_url %}
    </div>
  </div>

{% endblock %}